# services:
#     prod-ecommerce-nginx:
#         image: nginx:latest
#         restart: always
#         ports:
#             - "21443:443"
#         volumes:
#             - ./nginx.prod.conf:/etc/nginx/nginx.conf
#             - /etc/letsencrypt/archive/shop.advd.tech:/etc/nginx/ssl
#         networks:
#             - prod-net
#     prod-ecommerce-frontend:
#         build:
#             context: ./frontend/webform
#         ports:
#             # - '9002:80'
#             - '21092:80'
#         env_file:
#             - ./frontend/webform/.env
#         networks:
#             - prod-net
                

#     prod-ecommerce-backend:
#         build: ./backend/spring-server-v1
#         ports:
#             # - '9092:9090'
#             - '21093:9090'
#         depends_on:
#             - prod-ecommerce-db
#         environment:
#             - SPRING_DATASOURCE_URL=${DB_URL}
#             - SPRING_DATASOURCE_USERNAME=${DB_USER}
#             - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
#             - JWT_SECRET=${JWT_SECRET}
#             - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
#             - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
#             - BACKEND_SERVER_PORT=21093
#         networks:
#             - prod-net

#     prod-ecommerce-db:
#         image: postgres:latest
#         ports:
#             - '5434:5432'
#         environment:
#             - POSTGRES_DB=${DB_NAME}
#             - POSTGRES_USER=${DB_USER}
#             - POSTGRES_PASSWORD=${DB_PASSWORD}
#         networks:
#             prod-net

# networks:
#     prod-net:
#         driver: bridge
