services:
  frontend:
    build: ./frontend/webform
    dockerfile: Dockerfile
    ports:
      - '9001:80'  # Порт изменён для тестовой среды
    env_file:
      - ./frontend/webform/.env       # Конфигурационный файл среды

  backend:
    build: ./backend/spring-server-v1
    ports:
      - '9091:9090'  # Изменён порт для тестирования, чтобы не пересекаться с продакшеном
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - BACKEND_SERVER_PORT=9091  # Локальный порт backend сервера для тестирования

  db:
    image: postgres:latest
    ports:
      - '5433:5432'  # Порт для базы данных, не конфликтующий с `main`
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # volumes:
    #   - ./webform_data_dev:/var/lib/postgresql/data  # Отдельный volume для тестовой базы данных
