server:
  port: ${CATALOG_SERVICE_PORT}
  address: 0.0.0.0

spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create # will be changed to 'validate' in production
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: catalog-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.teipsum.shared.product"
    listener:
      type: single
      ack-mode: manual

#  cache:
#    type: redis
#    redis:
#      time-to-live: 300000 

logging:
  system:
    service.name: ${spring.application.name}
  level:
    com.teipsum.catalogservice: debug
    org.springframework.security: info
    org.hibernate.SQL: warn
    CATALOG: info
#    org.springframework.data.elasticsearch: warn

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS}
    # methods: "GET,OPTIONS"
    # headers: "Content-Type,Authorization"  #Already set by Spring Security (SecurityConfig)
    # max-age: 3600

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"