services:
  teipsum-docs:
    container_name: teipsum-docs
    image: swaggerapi/swagger-ui:v5.9.0
    environment:
      - VALIDATOR_URL=none
      - CONFIG_URL=/swagger-config.json
      # - "URLS_PRIMARY_NAME=\"TeIpsum API Docs\""
    volumes:
      - ./specs:/usr/share/nginx/html/api-docs:ro
    networks:
      - prod-net

networks:
  prod-net:
    external: true