services:  
  stage-user-service:
    container_name: stage-user-service
    build:
      context: ../..
      dockerfile: backend/user-service/Dockerfile
      args:
        SERVICE_NAME: user-service
    ports: ['22094:9095']
    image: stage-user-service:latest
    env_file: .env
    networks: [stage-net]

networks:
  stage-net:
    external: true