name: Deploy Admin Product Service

on:
  push:
    paths:
      - 'backend/catalog-service/**'
    branches:
      - main
      - develop

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service-reusable.yml
    with:
      SERVICE_NAME: catalog-service
      DEPLOY_ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'stage' }}
      GIT_BRANCH: ${{ github.ref == 'refs/heads/main' && 'main' || 'develop' }}
      COMPOSE_FILE: docker-compose.${{ github.ref == 'refs/heads/main' && 'prod' || 'stage' }}-catalog-service.yml
    secrets:
      PROJECT_DIR: ${{ secrets.PROJECT_DIR }}

      SSH_HOST: ${{ github.ref == 'refs/heads/main' && secrets.PROD_DEPLOY_HOST || secrets.STAGE_DEPLOY_HOST }}
      SSH_USER: ${{ github.ref == 'refs/heads/main' && secrets.PROD_DEPLOY_USER || secrets.STAGE_DEPLOY_USER }}
      SSH_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PROD_DEPLOY_KEY || secrets.STAGE_DEPLOY_KEY }}
      DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}

      SERVICE_SERVER_PORT: ${{ github.ref == 'refs/heads/main' && secrets.PROD_CATALOG_SERVICE_SERVER_PORT || secrets.STAGE_CATALOG_SERVICE_SERVER_PORT }}
      DB_NAME: ${{ github.ref == 'refs/heads/main' && secrets.PROD_CATALOG_SERVICE_DB_NAME || secrets.STAGE_CATALOG_SERVICE_DB_NAME }}
      DB_URL: ${{ github.ref == 'refs/heads/main' && secrets.PROD_CATALOG_SERVICE_DB_URL || secrets.STAGE_CATALOG_SERVICE_DB_URL }}
      DB_USER: ${{ github.ref == 'refs/heads/main' && secrets.PROD_CATALOG_SERVICE_DB_USER || secrets.STAGE_CATALOG_SERVICE_DB_USER }}
      DB_PASSWORD: ${{ github.ref == 'refs/heads/main' && secrets.PROD_CATALOG_SERVICE_DB_PASSWORD || secrets.STAGE_CATALOG_SERVICE_DB_PASSWORD }}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${{ github.ref == 'refs/heads/main' && secrets.PROD_KAFKA_BOOTSTRAP_SERVERS || secrets.STAGE_KAFKA_BOOTSTRAP_SERVERS }}

      CORS_ALLOWED_ORIGINS: ${{ github.ref == 'refs/heads/main' && secrets.PROD_AUTH_SERVICE_CORS_ALLOWED_ORIGINS || secrets.STAGE_AUTH_SERVICE_CORS_ALLOWED_ORIGINS }}
